# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'AutismApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AutismApp
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'

  target 'AutismAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AutismApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AutismApp-tvOS

  target 'AutismApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

